// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
  API: {
      GraphQL: {
        endpoint: process.env.REACT_APP_GRAPHQL_API_ENDPOINT,
        region: process.env.REACT_APP_GRAPHQL_REGION,
        defaultAuthMode: 'apiKey',
        apiKey: process.env.REACT_APP_APPSYNC_API_KEY
      }
  }
};

export default config;